config/routes.rb
Rails.application.routes.draw do

  get 'posts/search'

  # get 'sessions/new'

  root    "static_pages#home"
  get    '/about',    to:'static_pages#about'
  get    '/support',  to:'static_pages#support'
  get    '/recruit',  to:'static_pages#recruit'
  get    '/privacy',  to:'static_pages#privacy'
  get    '/term',     to:'static_pages#term'
  get    '/language', to:'static_pages#language'
  get    '/signup',   to:'users#new'
  post   '/',         to:'users#create'
  get    '/login',    to:'sessions#new'
  delete '/logout',   to:'sessions#destroy'
  post   '/login',    to:'sessions#create'

  resources :users do
    member do
      get :following, :followers, :like
    end
  end
  
  resources :microposts,          only: [:index, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  
  #get|post user_facebook_omniauth_callback_path -> users/omniauth_callbacks#facebook  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost.html.erb
<% if @search_microposts.any? %>
  <ul>
    <% @search_microposts.each do |micropost| %>
      <%= micropost.content %>
      <%= micropost.picture %>
    <% end %>
  </ul>
<% else %>
  <ul>
    <% @microposts.each do |micropost| %>
      <%= micropost.content %>
      <%= micropost.picture %>
    <% end %>
  </ul>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= @micropost = Micropost.new unless @micropost %>
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,imgage/jpg,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_search.html.erb
<!--search_form_forはform_forのRansack版-->
<!--https://qiita.com/fukuda_fu/items/58e3b5d9a776d98a62de-->
    <%= search_form_for @search, url:microposts_path do |f| %>]
      <div class="actions_small">
        <%= f.label :picture_cont, "画像に関するキーワード" %>
        <%= f.text_field :picture_cont %>
        <%= f.submit ("検索する"), class: "btn btn-primary" %>
      </div>
    <% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_stats_liked.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @micropost.liked.count %>
    </strong>
    いいね！
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.user_name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>