config/routes.rb
Rails.application.routes.draw do

  get 'posts/search'

  # get 'sessions/new'

  root    "static_pages#home"
  get    '/about',    to:'static_pages#about'
  get    '/support',  to:'static_pages#support'
  get    '/recruit',  to:'static_pages#recruit'
  get    '/privacy',  to:'static_pages#privacy'
  get    '/term',     to:'static_pages#term'
  get    '/language', to:'static_pages#language'
  get    '/signup',   to:'users#new'
  post   '/',         to:'users#create'
  get    '/login',    to:'sessions#new'
  delete '/logout',   to:'sessions#destroy'
  post   '/login',    to:'sessions#create'

  resources :users do
    member do
      get :following, :followers, :like
    end
  end
  
  resources :microposts,          only: [:index, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  
  #get|post user_facebook_omniauth_callback_path -> users/omniauth_callbacks#facebook  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div>
    <li><%= link_to "トップページ",   root_path %></li>
    <!--by <a href="http://www.michaelhartl.com/">Michael Hartl</a>-->
  </div>
  <% if logged_in? %>
    <div class ="actions">
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </div>
  <% end %>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Support", support_path %></li>
      <li><%= link_to "Recruit", recruit_path %></li>
      <li><%= link_to "Privacy", privacy_path %></li>
      <li><%= link_to "Term   ", term_path %></li>
      <li><%= link_to "Language",language_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!--= link_to "Insta_clone", '#', id: "logo" -->
    <nav>
      <!--= render 'shared/search' %>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              MyPage <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : 306835590230609,
          cookie     : true,
          xfbml      : true,
          version    : v5.0
        });
          
        FB.AppEvents.logPageView();   
          
      };
    
      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    
    <%= render 'layouts/header' %>
    <!--binding.pry -->
    <%= search_form_for @search, url:microposts_path do |f| %>]
      <div class="actions_small">
        <%= f.label :content_cont, "投稿に関するキーワード" %>
        <%= f.text_field :content_cont %>
        <%= f.label :picture_cont, "画像に関するキーワード" %>
        <%= f.text_field :picture_cont %>
        <%= f.submit ("検索する"), class: "btn btn-primary" %>
      </div>
    <% end %>
    
    <div class="container">
      <!--flashの書式を場合分けして設定-->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <p class="notice"><%= notice %></p>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>